### ISSUE TITLE
New downloader

### ISSUE THREAD

**Issue by dexter101010** [Jayapraveen/ITPro.Tv-Courses-downloader#1]
Hi buddy, 

Can you do another one for ine.com ? linuxacademy ?cloudacademy ?cbt-nuggets?

Kind regards!

**Comment by Jayapraveen** [comment]
Some of them need active subscription to look at the videos. I Will try to create when I get a chance.

**Comment by dexter101010** [comment]
> Some of them need active subscription to look at the videos. I Will try to create when I get a chance.

Hi buddy, 

If you need username/pass for ine, linuxacademy, cloudacademy or cbt-nuggets, just let me know.

**Comment by Jayapraveen** [comment]
Hi @dexter101010 , 
Thankyou for your offer. Unlike Itpro.tv some of the content platforms you mentioned dont have intricate DRM in place. Making downloader script opensource for those will lead to potential misuse/abuse of their services. A typical example would be Skillshare. You can DM me for further queries.

**Comment by dexter101010** [comment]
Do you have a skype account ? Or something where i can message you directly ?

**Comment by Jayapraveen** [comment]
I'm available on Discord as Jayapraveen#1284

**Comment by Kaatne-Wala-Kutta** [comment]
dester101010 or Jayapraveen
please anyone of you still have ine.com subscription?
please an urgent request

**Comment by Kaatne-Wala-Kutta** [comment]
anyone of you on discord?
please message me *ali*#4093
