### ISSUE TITLE
Token Entered is not valid!

### ISSUE THREAD

**Issue by nimesh09** [Jayapraveen/ITPro.Tv-Courses-downloader#11]
Hiii,

It's showing Token entered is not valid! when i run script. Please help me.
I'm monthly standard subscriber of ITproTv

![image](https://user-images.githubusercontent.com/36756508/117562819-769a5500-b0bf-11eb-9392-524859806df6.png)

**Comment by Jayapraveen** [comment]
Fixed in commit (9784d94)

**Comment by nimesh09** [comment]
Can you make video ??

**Comment by nimesh09** [comment]
I have another site networking.com and i have premium subscription can we work on that and how can i connect with you ?
