### ISSUE TITLE
Configuration File is missing

### ISSUE THREAD

**Issue by Backup420** [Jayapraveen/ITPro.Tv-Courses-downloader#12]
Tried multiple times with different tokens, still always get the error shown in screenshot. Any fix?

![powershell_bTBIuUdw0K](https://user-images.githubusercontent.com/83664515/118029842-75d21f00-b35c-11eb-918e-bb7a971a0ce0.png)

**Comment by nimesh09** [comment]
Rename config file "itProDownloaderConfig.json"  name to itProDownloader.json

it will work and if still you face issue than contact me telegram @NimEsh09

**Comment by Jayapraveen** [comment]
Fixed in commit b58e678.
