### ISSUE TITLE
Token Error!

### ISSUE THREAD

**Issue by Kooftness** [Jayapraveen/ITPro.Tv-Courses-downloader#14]
I copied the whole line below and pasted into the token line on config file. 

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2MGMxNzg4MDkzZDY5MzAwMDEwMTI5YjIiLCJhZG1pbiI6ZmFsc2UsImNvbnRlbnRzIjp7ImZyZWUiOnRydWUsImxpbWl0Q2F0ZWdvcmllcyI6ZmFsc2UsImxpbWl0Q291cnNlcyI6ZmFsc2UsImNhdGVnb3J5TGFiZWwiOiJGcmVlIENvdXJzZXMiLCJzZXJ2aWNlcyI6WyJsaXZlVmlldyIsImNoYXRWaWV3Il19LCJsYXN0bmFtZSI6Ik1hbmRlZ2FyIiwiZXhwIjoxNjIzNTM2NzYwLCJ1c2VyZ3JvdXBzIjpbIklUUHJvVFYiLCJUcmlhbCJdLCJ1c2VybmFtZSI6Im1hdHRoZXdtYW5kZWdhckBnbXguY29tIiwiaGlkZGVuQWNjZXNzIjpbXSwidXNlcklkIjoiMDUwMzk2NjItMjI3ZS00Zjk1LTgwZDktZTE0ZDUwMWEyYTY3IiwiaWF0IjoxNjIzNDUwMzYwLCJnZW5kZXIiOm51bGwsImludGVyY29tSGFzaCI6ImJkMzZlNGVmNzBhZTAzNjJmNTRkYzUxYTFiOGQyY2RlOTVkMzg5OGRjMDQ5ZTc5NzlmYWY5ZmIwODRiMGQ5NjMiLCJjb21wYW55IjpudWxsLCJwaG9uZW51bWJlciI6bnVsbCwiZmlyc3RuYW1lIjoiTWF0dGhldyIsImlkIjoiNjBjMTc4ODA5M2Q2OTMwMDAxMDEyOWIyIiwic2hpcnRTaXplIjpudWxsfQ.vgiBelloOjubPMbYWgu5An0EBCWzZ_Sv-qGWwX_xLbc","userId":"05039662-227e-4f95-80d9-e14d501a2a67","firstName":"Matthew","lastName":"Mandegar","services":["liveView","chatView"],"contents":{"free":true,"limitCategories":false,"limitCourses":false,"categoryLabel":"Free Courses"},"userGroups":["Free","ITProTV","Trial"],"hiddenAccess":[],"brand":{"externalId":"00002560-0000-3fa9-0000-1d61000035f3","name":"ITProTV"

  {
    "downloadQuality" : "1080p",
    "method" : "download",
    "downloadLocation": "./",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2MGMxNzg4MDkzZDY5MzAwMDEwMTI5YjIiLCJhZG1pbiI6ZmFsc2UsImNvbnRlbnRzIjp7ImZyZWUiOnRydWUsImxpbWl0Q2F0ZWdvcmllcyI6ZmFsc2UsImxpbWl0Q291cnNlcyI6ZmFsc2UsImNhdGVnb3J5TGFiZWwiOiJGcmVlIENvdXJzZXMiLCJzZXJ2aWNlcyI6WyJsaXZlVmlldyIsImNoYXRWaWV3Il19LCJsYXN0bmFtZSI6Ik1hbmRlZ2FyIiwiZXhwIjoxNjIzNTM2NzYwLCJ1c2VyZ3JvdXBzIjpbIklUUHJvVFYiLCJUcmlhbCJdLCJ1c2VybmFtZSI6Im1hdHRoZXdtYW5kZWdhckBnbXguY29tIiwiaGlkZGVuQWNjZXNzIjpbXSwidXNlcklkIjoiMDUwMzk2NjItMjI3ZS00Zjk1LTgwZDktZTE0ZDUwMWEyYTY3IiwiaWF0IjoxNjIzNDUwMzYwLCJnZW5kZXIiOm51bGwsImludGVyY29tSGFzaCI6ImJkMzZlNGVmNzBhZTAzNjJmNTRkYzUxYTFiOGQyY2RlOTVkMzg5OGRjMDQ5ZTc5NzlmYWY5ZmIwODRiMGQ5NjMiLCJjb21wYW55IjpudWxsLCJwaG9uZW51bWJlciI6bnVsbCwiZmlyc3RuYW1lIjoiTWF0dGhldyIsImlkIjoiNjBjMTc4ODA5M2Q2OTMwMDAxMDEyOWIyIiwic2hpcnRTaXplIjpudWxsfQ.vgiBelloOjubPMbYWgu5An0EBCWzZ_Sv-qGWwX_xLbc","userId":"05039662-227e-4f95-80d9-e14d501a2a67","firstName":"Matthew","lastName":"Mandegar","services":["liveView","chatView"],"contents":{"free":true,"limitCategories":false,"limitCourses":false,"categoryLabel":"Free Courses"},"userGroups":["Free","ITProTV","Trial"],"hiddenAccess":[],"brand":{"externalId":"00002560-0000-3fa9-0000-1d61000035f3","name":"ITProTV"}
}

**Comment by flyingdrnick** [comment]
You only need up to Lbc" the rest of the userid etc is not required

**Comment by Jayapraveen** [comment]
Please do not post your full token anywhere online. As mentioned by @flyingdrnick, use Only the token in the config file.
