### ISSUE TITLE
Token Error! Recheck and fix token in the configuration

### ISSUE THREAD

**Issue by Oshekher** [Jayapraveen/ITPro.Tv-Courses-downloader#16]
It's not working, showing token error but the token is correct.

**Comment by Oshekher** [comment]
{
    "downloadQuality" : "1080p",
    "method" : "download",
    "downloadLocation": "./",
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2MGM3ODgyOGI1NDk3ODAwMDEwOGIwMWUiLCJhZG1pbiI6ZmFsc2UsImNvbnRlbnRzIjp7ImZyZWUiOnRydWUsImxpbWl0Q2F0ZWdvcmllcyI6ZmFsc2UsImxpbWl0Q291cnNlxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWViODljYjdlIiwiY29tcGFueSI6bnVsbCwicGhvbmVudW1iZXIiOm51bGwsImZpcnN0bmFtZSI6IlNha3NoYW0iLCJpZCI6IjYwYzc4ODI4YjU0OTc4MDAwMTA4YjAxZSIsInNoaXJ0U2l6ZSI6bnVsbH0.tfJhYRR97_4uHRKjC7ROz10eDZG8b4MQbKMD9p0rfKw"

**Comment by Oshekher** [comment]
@Jayapraveen please help

**Comment by Budeestar** [comment]
@Oshekher have u got it bro? if yes please let know

**Comment by Oshekher** [comment]
@Budeestar tried many times differently but same issue happening and also author is not replying at all 😔

**Comment by Jayapraveen** [comment]
@Oshekher, What Subscription plan do you have? Is it a buisness plan ? The script was written and tested for Personal Subscriptions, And the downloader config sample you posted is missing the closing braces. So check for formatting issues.
