### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by Budeestar** [Jayapraveen/ITPro.Tv-Courses-downloader#17]
Token Error! Recheck and fix token in the configuration 
My error is this bro.
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2MGNjNTIwODExNzI2MjAwMDEwMWUxMjAiLCJhZG1pbiI6ZmFsc2UsImNvbnRlbnRzIjp7ImZyZWUiOnRydWUsImxpbWl0Q2F0ZWdvcmllcyI6ZmFsc2UsImxpbWl0Q291cnNlcyI6ZmFsc2UsImNhdGVnb3J5TGFiZWwiOiJGcmVlIENvdXJzZXMiLCJzZXJ2aWNlcyI6WyJsaXZlVmlldyIsImNoYXRWaWV3Il19LCJsYXN0bmFtZSI6Ik5pdGhpbiBZYWRhdiIsImV4cCI6MTYyNDA4OTQ4MSwidXNlcmdyb3VwcyI6WyJJVFByb1RWIiwiVHJpYWwiXSwidXNlcm5hbWUiOiJuaXRoaW4ueWFkYXYwMDEwQGdtYWlsLmNvbSIsImhpZGRlbkFjY2VzcyI6W10sInVzZXJJZCI6ImVkY2RhODA1LWFhOTQtNDIzYS05Mzk1LTQ4MGY0ZDQzYjExYSIsImlhdCI6MTYyNDAwMzA4MSwiZ2VuZGVyIjpudWxsLCJpbnRlcmNvbUhhc2giOiJhNzM4YjQ3OWIwODgyYTJlNDdlMWIxZmZiOTQ1MTI1MGUyZDkyNWMzN2ZlMmJiN2FkN2ZiMzFmOWRjNjIwZTgwIiwiY29tcGFueSI6bnVsbCwicGhvbmVudW1iZXIiOm51bGwsImZpcnN0bmFtZSI6IlBhbmR1Z2F5YWxhIiwiaWQiOiI2MGNjNTIwODExNzI2MjAwMDEwMWUxMjAiLCJzaGlydFNpemUiOm51bGx9.MCyvkUDaQOgAZrv_BuK7GiC7-VhokHHiyo3Ya5E3Cj8.
This is my token .
Please help me.

**Comment by Jayapraveen** [comment]
Please check if your downloader config file is like this:

{
    "downloadQuality" : "1080p",
    "method" : "download",
    "downloadLocation": "./",
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2MGNjNTIwODExNzI2MjAwMDEwMWUxMjAiLCJhZG1pbiI6ZmFsc2UsImNvbnRlbnRzIjp7ImZyZWUiOnRydWUsImxpbWl0Q2F0ZWdvcmllcyI6ZmFsc2UsImxpbWl0Q291cnNlcyI6ZmFsc2UsImNhdGVnb3J5TGFiZWwiOiJGcmVlIENvdXJzZXMiLCJzZXJ2aWNlcyI6WyJsaXZlVmlldyIsImNoYXRWaWV3Il19LCJsYXN0bmFtZSI6Ik5pdGhpbiBZYWRhdiIsImV4cCI6MTYyNDA4OTQ4MSwidXNlcmdyb3VwcyI6WyJJVFByb1RWIiwiVHJpYWwiXSwidXNlcm5hbWUiOiJuaXRoaW4ueWFkYXYwMDEwQGdtYWlsLmNvbSIsImhpZGRlbkFjY2VzcyI6W10sInVzZXJJZCI6ImVkY2RhODA1LWFhOTQtNDIzYS05Mzk1LTQ4MGY0ZDQzYjExYSIsImlhdCI6MTYyNDAwMzA4MSwiZ2VuZGVyIjpudWxsLCJpbnRlcmNvbUhhc2giOiJhNzM4YjQ3OWIwODgyYTJlNDdlMWIxZmZiOTQ1MTI1MGUyZDkyNWMzN2ZlMmJiN2FkN2ZiMzFmOWRjNjIwZTgwIiwiY29tcGFueSI6bnVsbCwicGhvbmVudW1iZXIiOm51bGwsImZpcnN0bmFtZSI6IlBhbmR1Z2F5YWxhIiwiaWQiOiI2MGNjNTIwODExNzI2MjAwMDEwMWUxMjAiLCJzaGlydFNpemUiOm51bGx9.MCyvkUDaQOgAZrv_BuK7GiC7-VhokHHiyo3Ya5E3Cj8"
}
