### ISSUE TITLE
Access to this video has been denied

### ISSUE THREAD

**Issue by dexter101010** [Jayapraveen/ITPro.Tv-Courses-downloader#2]
Hi, 

I have found that if i am trying to open a link from the extracted list, i receive this error : 

Access to this video has been denied

And when i am importing the list to IDM,  i receive an error message from IDM.

So can't download extracted videos from the extracted links

**Comment by Jayapraveen** [comment]
Hi @dexter101010  ,
Itpro.tv has drm enabled on their video files. They are using third party steaming service to serve content. The video urls are signed with a expiring timestamp usually of about ~12 hours. Try downloading soon after the script completes or modify the script to directly download the video content.
