### ISSUE TITLE
Script does not work   KeyError: 'token'

### ISSUE THREAD

**Issue by dexter101010** [Jayapraveen/ITPro.Tv-Courses-downloader#4]
When i am trying to run the script, i get the following : 

python itprotv.py
Traceback (most recent call last):
  File "itprotv.py", line 80, in <module>
    data_auth = ast.literal_eval(json.dumps({"Authorization":"Bearer "+login_data['token'],"user-agent":ua}))
KeyError: 'token'

**Comment by marvinej** [comment]
same.

**Comment by mahmoudshoaala** [comment]
same

**Comment by Jayapraveen** [comment]
Fixed in commit (9398229)
