### ISSUE TITLE
Token issue

### ISSUE THREAD

**Issue by mahmoudshoaala** [Jayapraveen/ITPro.Tv-Courses-downloader#6]
= RESTART: C:\Users\Hanafi\Downloads\ITPro.Tv-Courses-downloader-master\itprotv.py
Traceback (most recent call last):
  File "C:\Users\Hanafi\Downloads\ITPro.Tv-Courses-downloader-master\itprotv.py", line 80, in <module>
    data_auth = ast.literal_eval(json.dumps({"Authorization":"Bearer "+login_data['token'],"user-agent":ua}))
KeyError: 'token'

**Comment by xninaki** [comment]
same

**Comment by Jayapraveen** [comment]
Fixed in the commit (9398229).
