### ISSUE TITLE
Error when choosing course

### ISSUE THREAD

**Issue by R0bert0r** [Jayapraveen/ITPro.Tv-Courses-downloader#8]
Encountered the following error when choosing a course:

Enter your choice: 16
Traceback (most recent call last):
  File "/home/pi/Documents/Python/ITV.py", line 84, in <module>
    episodes = get_episodes(episodes["course"]["episodes"])
KeyError: 'course'
![Error](https://user-images.githubusercontent.com/81039112/111880231-8f6c7100-8980-11eb-8b50-345b98feeeb2.PNG)

please assist 

Thanks

**Comment by Jayapraveen** [comment]
Please check if the token you entered in login_data string is valid. Token validation will be added in next release of the script.

**Comment by Jayapraveen** [comment]
Try version 1.0.3 or later

**Comment by SteevenRodriguez** [comment]
The length of token changed to 928 for me, that solved the error.

**Comment by mrpanda1925** [comment]
Having a similar issue. Error message as follows.

Traceback (most recent call last):
  File "C:\users\Daddy Panda\desktop\ITProAlt\itprotv.py", line 143, in <module>
    episodes_download_links = get_download_links(episode_links,data_auth,resolution)
  File "C:\users\Daddy Panda\desktop\ITProAlt\itprotv.py", line 104, in get_download_links
    if (req_data["episode"][resolution] == None):
KeyError: 'episode'

Kindly advise. Thank you.

**Comment by Jayapraveen** [comment]
Fixed in commit b58e678.
